FROM postgres:latest

LABEL maintainer="admin@tunahanipek.com"
LABEL author="Tunahan Ipek"

RUN apt-get update -y
RUN apt-get install -y locales locales-all

ENV LC_ALL tr_TR.UTF-8
ENV LANG tr_TR.UTF-8
ENV LANGUAGE tr_TR.UTF-8